Project documented
pmsipilot/dashboard pull request #6
Opened 2018-11-06 11:53 UTC by NilinC

* README 
* Docker environment updated
* Makefile

2018-11-06 13:21 UTC, wixyvir requested changes

2018-11-06 13:21 UTC, wixyvir commented on Dockerfile
> +FROM node:alpine AS builder-back
This build stage is useless

2018-11-06 13:21 UTC, wixyvir commented on Makefile
> +	$(BIN_DIR)/browserify $(SRC_JS)/client/client.jsx --debug --outfile $(DIST_DIR)/dashboard.js --transform [babelify]
to be consistent, maybe define a `$(BROWSERIFY)` variable?

2018-11-06 13:21 UTC, wixyvir commented on README.md
> +Dashboard provides an interface to monitor job's status for continuous integration.
Should'nt we list what are these jobs ? Jenkins...

2018-11-08 08:26 UTC, Gwalchmei commented on README.md
> +# This task will create the docker image for the dashboard, install js dependancies and build css
I prefer smaller code blocks with only useful commands and the comments as plain text. It is easier to read and you can easily copy/paste to get started

2018-12-06 15:47 UTC, kevinbalicot commented on Dockerfile
> +FROM node:alpine AS builder-back
why ?

2018-12-06 17:16 UTC, wixyvir commented on Dockerfile
> +FROM node:alpine AS builder-back
Has been fixed

2018-12-06 17:17 UTC, wixyvir approved these changes

2018-12-06 17:18 UTC, desaintvincent approved these changes

2018-12-06 17:18 UTC, desaintvincent commented on app/js/server/server.js
>  app.get('/api/users/get', function (req, res) {
not needed anymore, and `users.json` should be deleted

2018-12-07 08:46 UTC, merged